fixing pr_number

diff --git a/.github/workflows/git_workflow_process.yaml b/.github/workflows/git_workflow_process.yaml
--- a/.github/workflows/git_workflow_process.yaml
+++ b/.github/workflows/git_workflow_process.yaml
@@ -150,7 +150,7 @@ jobs:
             BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
             echo "Checking for PR on branch: $BRANCH_NAME"
 
-            PR_NUMBER=$(gh pr list --repo "bfidatadigipres/checksum_scripts" --head "breaking_github1" --state open --json number --jq '.[0].number' 2>/dev/null || echo "error")
+            PR_NUMBER=$(gh pr list --repo "bfidatadigipres/checksum_scripts" --head "$BRANCH_NAME" --state open --json number --jq '.[0].number' 2>/dev/null || echo "error")
 
             echo "Found PR number: $PR_NUMBER"
             if [  "$PR_NUMBER" != "error" ]; then
