adding new emojis: and fixinf pr_number

diff --git a/.github/workflows/git_workflow_process.yaml b/.github/workflows/git_workflow_process.yaml
--- a/.github/workflows/git_workflow_process.yaml
+++ b/.github/workflows/git_workflow_process.yaml
@@ -3,7 +3,8 @@ name: Automated Git Workflow used by developers
 on:
   push:
     branches: ['*']
-  pull_request:
+  pull_request_target:
+    types: [opened, synchronize, reopened]
 
 permissions:
   contents: write  # Changed to write to allow pushing changes
@@ -150,7 +151,7 @@ jobs:
             BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
             echo "Checking for PR on branch: $BRANCH_NAME"
 
-            PR_NUMBER=$(gh pr list --repo "bfidatadigipres/checksum_scripts" --head "breaking_github1" --state open --json number --jq '.[0].number' 2>/dev/null || echo "error")
+            PR_NUMBER=$(gh pr list --repo "bfidatadigipres/checksum_scripts" --head "${{ github.repository_owner }}:${{ github.ref_name }}" --state open --json number --jq '.[0].number' 2>/dev/null || echo "error")
 
             echo "Found PR number: $PR_NUMBER"
             if [  "$PR_NUMBER" != "error" ]; then
